services:
    app:
        build: .
        container_name: "${APP_NAME}"
        ports: ["${APP_PORT}:8000"]
        depends_on: [db]
        env_file:
            - .env
        networks: ["internal_net"]

    db:
        image: ${DB_IMAGE}
        container_name: ${DB_CONTAINER_NAME}
        ports: ["${DB_PORT_OUT}:${DB_PORT}"]
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        volumes: ["db_data:/var/lib/mysql"]
        command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_unicode_ci
        networks: ["internal_net"]

    node:
        image: node:20-alpine
        working_dir: /var/www/html
        volumes: [".:/var/www/html"]
        command: sh -c "npm install && npm run dev"
        networks: ["internal_net"]
        profiles: ["dev"]

volumes:
    db_data:

networks:
    internal_net:
        name: ${DB_NETWORK}
        driver: bridge
